### ISSUE TITLE
Enable extra labels for identifying server groups

### ISSUE THREAD

**Issue by paulojmdias** [paulojmdias/lokxy#15]
Allow users to define custom labels for server groups to improve identification and filtering in logs. Example:

```yaml
server_groups:
  - name: "Loki 1"
    url: "http://localhost:3100"
    timeout: 30
    headers:
      Authorization: "Bearer <token>"
      X-Scope-OrgID: org1
   labels:
     __sg__: loki1
```

Tasks:
- Add support for defining extra labels in the config.
- Ensure labels are applied to logs consistently.
- Update documentation with usage examples.
