### ISSUE TITLE
Issue with Query in Cluster of Loki (read target)

### ISSUE THREAD

**Issue by iamhalje** [paulojmdias/lokxy#6]
we have different Loki clusters set up: one for standalone instances and another for clusters with read/write/backend targets, version across all instances is 3.3.2.

when I send a request from Grafana (v11.4.0, or other versions) to standalone instances via Lokxy, all requests work correctly, however, when send a request directly to the read target via Lokxy, encounter an issue.

**Error Details**:

when querying ```{service="someservice"}```, I get the following error:

```
ReadString: expects " or n, but found [, error found in #10 byte of ...|":52}}"],["174030457|..., bigger context ...|entId\":\"a68f4d9276663e08\",\"ThreadId\":52}}"],["1740304579939171000","{\"Time\":\"2025-02-23T14:5|...
```

however, when querying ```{service="someservice"} | json```, it works fine.

additionally, when I use curl directly on the same query via lokxy, receive the correct response, and the JSON is properly parsed.

**Possible Cause**:

issue seems to reverse problem when remove the handling of encodingFlags in the code:

ref: https://github.com/paulojmdias/lokxy/blob/main/pkg/proxy/handler/query.go#L47-L55

mean ```{service="someservice"} | json``` not working, but working ```{service="someservice"}```.

**Behavior**:

-     If Grafana sends the request directly to the read target, everything works.
-     The issue only occurs when the request goes through Grafana -> Lokxy -> Read target.

i haven't included debug logs here because they don't seem to provide additional insights, Lokxy doesn't show any errors, and everything seems to parse correctly, it might be related to HTTP headers or something else in request/response.

**Comment by paulojmdias** [comment]
HI @iamhalje,

Thanks for opening the issue.

I will try to reproduce the issue and come back here with the next steps 🙌

**Comment by paulojmdias** [comment]
Hi @iamhalje,

My current setup also includes read/write/backend targets and I cannot reproduce the issue you are facing. Can you please share the Lokxy logs?

Can you also please share your current configuration file?

Thanks

**Comment by iamhalje** [comment]
@paulojmdias hello, yep sure

Lokxy config
```
server_groups:
  - name: "Loki Read Target"
    # read-target
    url: "http://loki03-test:3100"
    timeout: 310
    headers:
      X-Scope-OrgID: "default"

logging:
  level: "info"
  format: "logfmt"
```

[lokxy.log](https://github.com/user-attachments/files/19011545/lokxy.log)

[loki.log](https://github.com/user-attachments/files/19011546/loki.log)

@paulojmdias can i see your Loki config?

**Comment by paulojmdias** [comment]
@iamhalje the config is similiar like yours 

```yaml
server_groups:
  - name: "Loki 1"
    url: "https://loki1:3100"
    timeout: 60
    headers:
      X-Scope-OrgID: "tenant1"
    http_client_config:
      tls_config:
        insecure_skip_verify: true
  - name: "Loki 2"
    url: "https://loki2:3100"
    timeout: 60
    headers:
      X-Scope-OrgID: "tenant2"
    http_client_config:
      tls_config:
        insecure_skip_verify: true
  - name: "Loki 3"
    url: "https://loki3:3100"
    timeout: 60
    headers:
      X-Scope-OrgID: "tenant3"
    http_client_config:
      tls_config:
        insecure_skip_verify: true

logging:
  level: "info"
  format: "json"
```

The Lokxy version you are using is the latest one? Asking because i still haven't added the version to log at startup.

Each Loki entry above is on read/write/backend targets setup.

Is it also possible to do the query using curl and paste here the output?

Like below

```sh
curl "http://lokxy:3100/loki/api/v1/query_range?query={service=\"someservice\"}"
```
